### ISSUE TITLE
Can't find class biz.donvi.jakesRTP.SafeLocationUtils_12 upon load (1.18-pre8)

### ISSUE THREAD

**Issue by quiquelhappy** [donvi-bz/JakesRTP#12]
Hey!
I've been getting an error upon load. I don't know if this is being caused by using 1.18-pre8 spigot or if this was present before. I'll make sure to test it later today on previous versions:
```
[07:19:26] [[J-RTP] Loc Cache Filler/INFO]: [J-RTP] [J-RTP] LCF Started.
[07:19:26] [[J-RTP] Loc Cache Filler/WARN]: java.lang.ClassNotFoundException: biz.donvi.jakesRTP.SafeLocationUtils_12
[07:19:26] [[J-RTP] Loc Cache Filler/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[07:19:26] [[J-RTP] Loc Cache Filler/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[07:19:26] [[J-RTP] Loc Cache Filler/WARN]:     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[07:19:26] [[J-RTP] Loc Cache Filler/WARN]:     at java.base/java.lang.Class.forName0(Native Method)
[07:19:26] [[J-RTP] Loc Cache Filler/WARN]:     at java.base/java.lang.Class.forName(Class.java:375)
[07:19:26] [[J-RTP] Loc Cache Filler/WARN]:     at biz.donvi.jakesRTP.SafeLocationUtils.<clinit>(SafeLocationUtils.java:27)
[07:19:26] [[J-RTP] Loc Cache Filler/WARN]:     at biz.donvi.jakesRTP.SafeLocationFinderOtherThread.dropToGround(SafeLocationFinderOtherThread.java:64)
[07:19:26] [[J-RTP] Loc Cache Filler/WARN]:     at biz.donvi.jakesRTP.SafeLocationFinder.moveToStart(SafeLocationFinder.java:161)
[07:19:26] [[J-RTP] Loc Cache Filler/WARN]:     at biz.donvi.jakesRTP.SafeLocationFinder.tryAndMakeSafe(SafeLocationFinder.java:79)
[07:19:26] [[J-RTP] Loc Cache Filler/WARN]:     at biz.donvi.jakesRTP.RandomTeleporter.getRtpLocation(RandomTeleporter.java:424)
[07:19:26] [[J-RTP] Loc Cache Filler/WARN]:     at biz.donvi.jakesRTP.RandomTeleporter.fillQueue(RandomTeleporter.java:480)
[07:19:26] [[J-RTP] Loc Cache Filler/WARN]:     at biz.donvi.jakesRTP.LocationCacheFiller.run(LocationCacheFiller.java:41)
[07:19:26] [[J-RTP] Loc Cache Filler/WARN]:     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82)
[07:19:26] [[J-RTP] Loc Cache Filler/WARN]:     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[07:19:26] [[J-RTP] Loc Cache Filler/WARN]:     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[07:19:26] [[J-RTP] Loc Cache Filler/WARN]:     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[07:19:26] [[J-RTP] Loc Cache Filler/WARN]:     at java.base/java.lang.Thread.run(Thread.java:833)
```

Other than this, I couldn't find any bugs so far in 1.18-pre8

**Comment by quiquelhappy** [comment]
still hapens on rc-3

**Comment by NathanAdhitya** [comment]
J-RTP seems to be working normally for me in 1.18.1. Server is running 3363-Spigot-f65de01-e36f759.

**Comment by donvi-bz** [comment]
My guess is that the thing I used to check the Minecraft version gave me a -1 instead of an 18 due to the pre-release not being in the normal format,. Then the plugin probably tried to load the 1.12.2 compatibility module because -1 is less than 12. So yeah, should be a non-issue.
