### ISSUE TITLE
Exception without  ChunkyBorder

### ISSUE THREAD

**Issue by blockswerker** [donvi-bz/JakesRTP#15]
Is ChunkyBorder a prerequisite for Jakes-RTP now? v.0.14.7 generates this error on Paper #402 1.17.1 but v.0.14.5 does not.

```[20:28:07] [Server thread/INFO]: [J-RTP] Enabling JakesRTP v0.14.7
[20:28:07] [Server thread/ERROR]: Error occurred while enabling JakesRTP v0.14.7 (Is it up to date?)
java.lang.NoClassDefFoundError: org/popcraft/chunkyborder/ChunkyBorder
	at biz.donvi.jakesRTP.WorldBorderPluginHook$ChunkyBorderHook.getInstance(WorldBorderPluginHook.java:155) ~[JakesRTP-v0.14.7.jar:?]
	at biz.donvi.jakesRTP.WorldBorderPluginHook$ChunkyBorderHook.isUsable(WorldBorderPluginHook.java:144) ~[JakesRTP-v0.14.7.jar:?]
	at biz.donvi.jakesRTP.WorldBorderPluginHook.findHook(WorldBorderPluginHook.java:39) ~[JakesRTP-v0.14.7.jar:?]
	at biz.donvi.jakesRTP.WorldBorderPluginHook.<init>(WorldBorderPluginHook.java:26) ~[JakesRTP-v0.14.7.jar:?]
	at biz.donvi.jakesRTP.JakesRtpPlugin.onEnable(JakesRtpPlugin.java:68) ~[JakesRTP-v0.14.7.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-402]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-402]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-402]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-402]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-402]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-402]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-402]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-402]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-402]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.popcraft.chunkyborder.ChunkyBorder
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[patched_1.17.1.jar:git-Paper-402]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-402]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 15 more
[20:28:07] [Server thread/INFO]: [J-RTP] Disabling JakesRTP v0.14.7
[20:28:07] [Server thread/ERROR]: Error occurred while disabling JakesRTP v0.14.7 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "biz.donvi.jakesRTP.LocationCacheFiller.markAsOver()" because "biz.donvi.jakesRTP.JakesRtpPlugin.locFinderRunnable" is null
	at biz.donvi.jakesRTP.JakesRtpPlugin.onDisable(JakesRtpPlugin.java:89) ~[JakesRTP-v0.14.7.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.17.1.jar:git-Paper-402]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[patched_1.17.1.jar:git-Paper-402]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[patched_1.17.1.jar:git-Paper-402]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Paper-402]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-402]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-402]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-402]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-402]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-402]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-402]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-402]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]```
`

**Comment by donvi-bz** [comment]
Ah god damn it, no. Thanks for the report. Will fix fast.

**Comment by donvi-bz** [comment]
Was a two line fix
