### ISSUE TITLE
Bug: HEX color console error

### ISSUE THREAD

**Issue by ChiboYen** [donvi-bz/JakesRTP#7]
```
org.bukkit.command.CommandException: Unhandled exception executing command 'jakesrtp:rtp-admin' in plugin JakesRTP v0.13.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Purpur-1059]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.5.jar:git-Purpur-1059]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Purpur-1059]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2298) ~[patched_1.16.5.jar:git-Purpur-1059]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2113) ~[patched_1.16.5.jar:git-Purpur-1059]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2066) ~[patched_1.16.5.jar:git-Purpur-1059]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Purpur-1059]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Purpur-1059]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1059]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1059]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1059]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1059]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1059]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1325) ~[patched_1.16.5.jar:git-Purpur-1059]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1318) ~[patched_1.16.5.jar:git-Purpur-1059]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1059]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Purpur-1059]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Purpur-1059]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1059]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: No group 1
        at java.util.regex.Matcher.start(Matcher.java:483) ~[?:?]
        at java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1091) ~[?:?]
        at java.util.regex.Matcher.appendReplacement(Matcher.java:998) ~[?:?]
        at java.util.regex.Matcher.replaceAll(Matcher.java:1182) ~[?:?]
        at biz.donvi.jakesRTP.GeneralUtil.replaceNewColors(GeneralUtil.java:126) ~[?:?]
        at biz.donvi.jakesRTP.Messages.reformat(Messages.java:74) ~[?:?]
        at biz.donvi.jakesRTP.Messages.addMap(Messages.java:62) ~[?:?]
        at biz.donvi.jakesRTP.JakesRtpPlugin.loadMessageMap(JakesRtpPlugin.java:257) ~[?:?]
        at biz.donvi.jakesRTP.CmdRtpAdmin.subReloadMessages(CmdRtpAdmin.java:64) ~[?:?]
        at biz.donvi.jakesRTP.CmdRtpAdmin.onCommand(CmdRtpAdmin.java:35) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Purpur-1059]
        ... 19 more
```

This happens when I try to use hex colors in the `language-settings.yml`

```
need-to-wait-for-cooldown: '{#00FFC8}Test {0}'
```

**Comment by donvi-bz** [comment]
This has now been fixed for v0.13.10.
